services:
  summary_service:
    container_name: summary_service
    hostname: summary_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    environment:
      - PORT=50053
      - MONGODB_URI=mongodb+srv://Jda:21977Jda@cluster0.ikgmr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - KAFKA_BROKER=broker:29092
    networks:
      - app_network

networks:
  app_network:
    external: true