# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import summary_pb2 as summary__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in summary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SummaryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNews = channel.unary_unary(
                '/summaryservice.SummaryService/GetNews',
                request_serializer=summary__pb2.SummaryNewsRequest.SerializeToString,
                response_deserializer=summary__pb2.SummaryNewsResponse.FromString,
                _registered_method=True)
        self.UpdateNews = channel.unary_unary(
                '/summaryservice.SummaryService/UpdateNews',
                request_serializer=summary__pb2.SummaryNewsRequest.SerializeToString,
                response_deserializer=summary__pb2.UpdateNewsResponse.FromString,
                _registered_method=True)
        self.DeleteNews = channel.unary_unary(
                '/summaryservice.SummaryService/DeleteNews',
                request_serializer=summary__pb2.SummaryNewsRequest.SerializeToString,
                response_deserializer=summary__pb2.DeleteNewsResponse.FromString,
                _registered_method=True)


class SummaryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteNews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SummaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNews': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNews,
                    request_deserializer=summary__pb2.SummaryNewsRequest.FromString,
                    response_serializer=summary__pb2.SummaryNewsResponse.SerializeToString,
            ),
            'UpdateNews': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateNews,
                    request_deserializer=summary__pb2.SummaryNewsRequest.FromString,
                    response_serializer=summary__pb2.UpdateNewsResponse.SerializeToString,
            ),
            'DeleteNews': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteNews,
                    request_deserializer=summary__pb2.SummaryNewsRequest.FromString,
                    response_serializer=summary__pb2.DeleteNewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'summaryservice.SummaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('summaryservice.SummaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SummaryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summaryservice.SummaryService/GetNews',
            summary__pb2.SummaryNewsRequest.SerializeToString,
            summary__pb2.SummaryNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summaryservice.SummaryService/UpdateNews',
            summary__pb2.SummaryNewsRequest.SerializeToString,
            summary__pb2.UpdateNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteNews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/summaryservice.SummaryService/DeleteNews',
            summary__pb2.SummaryNewsRequest.SerializeToString,
            summary__pb2.DeleteNewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
